//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_Payout
    {
        public int Artist_ID { get; set; }
        public Nullable<double> Money_Paid_Out { get; set; }
        public Nullable<int> Streaming_Money { get; set; }
        public Nullable<int> Merch_Money { get; set; }
        public Nullable<double> Other { get; set; }
    
        public virtual Artist_Info Artist_Info { get; set; }
        public virtual Artist_Merch Artist_Merch { get; set; }
        public virtual Music_Earnings Music_Earnings { get; set; }
    }
}
