//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_Merch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist_Merch()
        {
            this.Artist_Payout = new HashSet<Artist_Payout>();
        }
    
        public int Merch_ID { get; set; }
        public string UPC { get; set; }
        public Nullable<int> Artist_ID { get; set; }
        public double Cost_Per_Unit { get; set; }
        public Nullable<int> Units_Sold { get; set; }
        public string Type_ { get; set; }
        public Nullable<double> Selling_Price { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Artist_Info Artist_Info { get; set; }
        public virtual Music_Release Music_Release { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artist_Payout> Artist_Payout { get; set; }
    }
}
