//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_Contact
    {
        public string Email { get; set; }
        public Nullable<int> Phone_Number { get; set; }
        public string Discord { get; set; }
        public int Artist_ID { get; set; }
    
        public virtual Artist_Info Artist_Info { get; set; }
    }
}
