//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Label_DatabaseEntities : DbContext
    {
        public Label_DatabaseEntities()
            : base("name=Label_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist_Contact> Artist_Contact { get; set; }
        public virtual DbSet<Artist_Info> Artist_Info { get; set; }
        public virtual DbSet<Artist_Merch> Artist_Merch { get; set; }
        public virtual DbSet<Artist_Payout> Artist_Payout { get; set; }
        public virtual DbSet<Artist_Socials> Artist_Socials { get; set; }
        public virtual DbSet<Music_Earnings> Music_Earnings { get; set; }
        public virtual DbSet<Music_Release> Music_Release { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Song_Info> Song_Info { get; set; }
        public virtual DbSet<wpfArtist_Info> wpfArtist_Info { get; set; }
    }
}
