//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music_Release
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music_Release()
        {
            this.Artist_Merch = new HashSet<Artist_Merch>();
            this.Song_Info = new HashSet<Song_Info>();
        }
    
        public string UPC { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public Nullable<int> No_Of_Tracks { get; set; }
        public Nullable<int> Length_ { get; set; }
        public string Main_Age { get; set; }
        public string Main_Gender { get; set; }
        public Nullable<int> Internal_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artist_Merch> Artist_Merch { get; set; }
        public virtual Music_Earnings Music_Earnings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Song_Info> Song_Info { get; set; }
    }
}
