//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppp
{
    using System;
    using System.Collections.Generic;
    
    public partial class wpfArtist_Info
    {
        public int ID { get; set; }
        public string Artist_Name { get; set; }
        public string Real_Name { get; set; }
        public string Nationality { get; set; }
    }
}
